# 第五章 pandas入门

In [3]:
import pandas as pd

In [4]:
from pandas import Series, DataFrame

In [5]:
import numpy as np

# 5.1 pandas 的数据结构介绍

## Series

Series 是一种类似于一维数组的对象，它由一组数据(各种 NumPy 数据类型) 以及一组与之相关的数据标签(即索引)组成。

In [3]:
obj = pd.Series([4, 7, -5, 3])

In [4]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [5]:
obj.values

array([ 4,  7, -5,  3])

In [6]:
obj.index  # like range(4)

RangeIndex(start=0, stop=4, step=1)

创建的 Series 带有一个可以对各个数据点进行标记的索引:

In [7]:
obj2 = pd.Series([4, 7, -5, 3], index=['d', 'b', 'a', 'c'])

In [8]:
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [9]:
obj2.index

Index(['d', 'b', 'a', 'c'], dtype='object')

选取 Series 中的单个或一组值:

In [10]:
obj2['a']

-5

In [11]:
obj2['d'] = 6

In [12]:
obj2[['c', 'a', 'd']]

c    3
a   -5
d    6
dtype: int64

In [13]:
obj2[obj2 > 0]

d    6
b    7
c    3
dtype: int64

In [14]:
obj2 * 2

d    12
b    14
a   -10
c     6
dtype: int64

In [17]:
np.exp(obj2)

d     403.428793
b    1096.633158
a       0.006738
c      20.085537
dtype: float64

 Series 看成是一个定长的有序字典，因为它是索引值到数据值的一个 映射。它可以用在许多原本需要字典参数的函数中:

In [18]:
'b' in obj2

True

In [19]:
'e' in obj2

False

数据被存放在一个 Python 字典中，也可以直接通过这个字典来创建 Series:

In [22]:
sdata = {'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}

In [23]:
obj3 = pd.Series(sdata)

In [24]:
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

Series 中的索引就是原字典的键(有序排列)。 你可以传入排好序的字典的键以改变顺序:

In [26]:
states = ['California', 'Ohio', 'Oregon', 'Texas']

In [27]:
obj4 = pd.Series(sdata, index=states)

In [28]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

pandas 的 isnull 和 notnull 函数可用于检测缺失数据:

In [29]:
pd.isnull(obj4)  

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [30]:
pd.notnull(obj4)

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [31]:
obj4.isnull()

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

Series 最重要的一个功能是，它会根据运算的索引标签自 动对齐数据:

In [32]:
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [33]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [34]:
obj3 + obj4

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

Series 对象本身及其索引都有一个 name 属性：

In [35]:
obj4.name = 'population'

In [36]:
obj4.index.name = 'state'

In [37]:
obj4

state
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

Series 的索引可以通过赋值的方式就地修改:

In [38]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [39]:
obj.index = ['Bob', 'Steve', 'Jeff', 'Ryan']

In [40]:
obj

Bob      4
Steve    7
Jeff    -5
Ryan     3
dtype: int64

## DataFrame

DataFrame 是一个表格型的数据结构，它含有一组有序的列，每列可以是不同 的值类型(数值、字符串、布尔值等)。

建 DataFrame 的办法有很多，最常用的一种是直接传入一个由等长列表或 NumPy 数组组成的字典:

In [41]:
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada',
'Nevada'],
        'year': [2000, 2001, 2002, 2001, 2002, 2003],
        'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}
frame = pd.DataFrame(data)

In [42]:
frame

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

对于特别大的 DataFrame，head 方法会选取前五行:

In [43]:
frame.head()

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

如果指定了列序列，则 DataFrame 的列就会按照指定顺序进行排列:

In [44]:
pd.DataFrame(data, columns=['year', 'state', 'pop'])

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

如果传入的列在数据中找不到，就会在结果中产生缺失值:

In [45]:
frame2 = pd.DataFrame(data, columns=['year', 'state', 'pop',
'debt'],
                      index=['one', 'two', 'three', 'four', 'five', 'six'])

In [46]:
frame2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN
six    2003  Nevada  3.2  NaN

In [47]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [48]:
frame2.index

Index(['one', 'two', 'three', 'four', 'five', 'six'], dtype='object')

通过类似字典标记的方式或属性的方式，可以将 DataFrame 的列获取为一个 Series:

In [49]:
frame2['state']

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
six      Nevada
Name: state, dtype: object

In [50]:
frame2.year

one      2000
two      2001
three    2002
four     2001
five     2002
six      2003
Name: year, dtype: int64

remeber：frame2[column]适用于任何列的名，但是 frame2.column 只有在列名是一个合 理的 Python 变量名时才适用。

行也可以通过位置或名称的方式进行获取，比如用 loc 属性(稍后将对此进行 详细讲解):

In [51]:
frame2.loc['three']

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object

列可以通过赋值的方式进行修改。例如，我们可以给那个空的"debt"列赋上一 个标量值或一组值:

In [52]:
frame2['debt'] = 16.5

In [53]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5  16.5
two    2001    Ohio  1.7  16.5
three  2002    Ohio  3.6  16.5
four   2001  Nevada  2.4  16.5
five   2002  Nevada  2.9  16.5
six    2003  Nevada  3.2  16.5

In [54]:
frame2['debt'] = np.arange(6.)

In [55]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   0.0
two    2001    Ohio  1.7   1.0
three  2002    Ohio  3.6   2.0
four   2001  Nevada  2.4   3.0
five   2002  Nevada  2.9   4.0
six    2003  Nevada  3.2   5.0

将列表或数组赋值给某个列时，其长度必须跟 DataFrame 的长度相匹配。如果 赋值的是一个 Series，就会精确匹配 DataFrame 的索引，所有的空位都将被填 上缺失值:

In [56]:
val = pd.Series([-1.2, -1.5, -1.7], index=['two', 'four', 'five'])

In [57]:
frame2['debt'] = val

In [58]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7
six    2003  Nevada  3.2   NaN

为不存在的列赋值会创建出一个新列。关键字 del 用于删除列。
作为 del 的例子，我先添加一个新的布尔值的列，state 是否为'Ohio':

In [59]:
frame2['eastern'] = frame2.state == 'Ohio'

In [60]:
frame2

year   state  pop  debt  eastern
one    2000    Ohio  1.5   NaN     True
two    2001    Ohio  1.7  -1.2     True
three  2002    Ohio  3.6   NaN     True
four   2001  Nevada  2.4  -1.5    False
five   2002  Nevada  2.9  -1.7    False
six    2003  Nevada  3.2   NaN    False

注意:不能用 frame2.eastern 创建新的列。

del 方法可以用来删除这列:

In [61]:
del frame2['eastern']

In [62]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

另一种常见的数据形式是嵌套字典:

In [63]:
pop = {'Nevada': {2001: 2.4, 2002: 2.9},
       'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}}

如果嵌套字典传给 DataFrame，pandas 就会被解释为:外层字典的键作为列， 内层键则作为行索引:

In [64]:
frame3 = pd.DataFrame(pop)

In [65]:
frame3

Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7
2002     2.9   3.6

你也可以使用类似 NumPy 数组的方法，对 DataFrame 进行转置(交换行和 列):

In [66]:
frame3.T

2000  2001  2002
Nevada   NaN   2.4   2.9
Ohio     1.5   1.7   3.6

内层字典的键会被合并、排序以形成最终的索引。如果明确指定了索引，则不
会这样:

In [67]:
pd.DataFrame(pop, index=[2001, 2002, 2003])

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2003     NaN   NaN

由 Series 组成的字典差不多也是一样的用法:

In [68]:
pdata = {'Ohio': frame3['Ohio'][:-1],
         'Nevada': frame3['Nevada'][:2]}

In [69]:
pd.DataFrame(pdata)

Ohio  Nevada
2000   1.5     NaN
2001   1.7     2.4

如果设置了 DataFrame 的 index 和 columns 的 name 属性，则这些信息也会被显 示出来

In [70]:
frame3.index.name = 'year'; frame3.columns.name = 'state'

In [71]:
frame3

state  Nevada  Ohio
year               
2000      NaN   1.5
2001      2.4   1.7
2002      2.9   3.6

In [73]:
frame3.values

array([[nan, 1.5],
       [2.4, 1.7],
       [2.9, 3.6]])

如果 DataFrame 各列的数据类型不同，则值数组的 dtype 就会选用能兼容所有 列的数据类型:

In [77]:
frame2.values

array([[2000, 'Ohio', 1.5, nan],
       [2001, 'Ohio', 1.7, -1.2],
       [2002, 'Ohio', 3.6, nan],
       [2001, 'Nevada', 2.4, -1.5],
       [2002, 'Nevada', 2.9, -1.7],
       [2003, 'Nevada', 3.2, nan]], dtype=object)

## 索引对象

In [78]:
obj = pd.Series(range(3), index=['a', 'b', 'c'])

In [79]:
index = obj.index

In [80]:
index

Index(['a', 'b', 'c'], dtype='object')

In [81]:
index[1:]

Index(['b', 'c'], dtype='object')

Index 对象是不可变的，因此用户不能对其进行修改:

In [83]:
index[1] = 'd' # TypeError   无法变更修改

TypeError: Index does not support mutable operations

不可变可以使 Index 对象在多个数据结构之间安全共享:

In [84]:
labels = pd.Index(np.arange(3))

In [85]:
labels

Int64Index([0, 1, 2], dtype='int64')

In [86]:
obj2 = pd.Series([1.5, -2.5, 0], index=labels)

In [87]:
obj2

0    1.5
1   -2.5
2    0.0
dtype: float64

In [88]:
obj2.index is labels

True

Index 的功能也类似一个固定大小的集合:

In [89]:
frame3

state  Nevada  Ohio
year               
2000      NaN   1.5
2001      2.4   1.7
2002      2.9   3.6

In [90]:
frame3.columns

Index(['Nevada', 'Ohio'], dtype='object', name='state')

In [91]:
'Ohio' in frame3.columns

True

In [92]:
2003 in frame3.index

False

与 python 的集合不同，pandas 的 Index 可以包含重复的标签:

In [94]:
dup_labels = pd.Index(['foo', 'foo', 'bar', 'bar'])

In [95]:
dup_labels

Index(['foo', 'foo', 'bar', 'bar'], dtype='object')

index有自己特定的属性和方法

# 5.2 基本功能

操作 Series 和 DataFrame 中的数据的基本手段

## 重新索引

In [96]:
obj = pd.Series([4.5, 7.2, -5.3, 3.6], index=['d', 'b', 'a',
'c'])

In [97]:
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

用该 Series 的 reindex 将会根据新索引进行重排。如果某个索引值当前不存 在，就引入缺失值:

In [98]:
obj2 = obj.reindex(['a', 'b', 'c', 'd', 'e'])

In [99]:
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64


对于时间序列这样的有序数据，重新索引时可能需要做一些插值处理。

In [101]:
obj3 = pd.Series(['blue', 'purple', 'yellow'], index=[0, 2,
4])


In [102]:
obj3

0      blue
2    purple
4    yellow
dtype: object

In [103]:
obj3.reindex(range(6), method='ffill')  #使用 ffill 可以实现前向值填充:

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

借助 DataFrame，reindex 可以修改(行)索引和列。只传递一个序列时，会重 新索引结果的行:

In [104]:
frame = pd.DataFrame(np.arange(9).reshape((3, 3)),
                     index=['a', 'c', 'd'],
                     columns=['Ohio', 'Texas','California'])


In [105]:
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [107]:
frame2 = frame.reindex(['a', 'b', 'c', 'd'])

In [108]:
frame2

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

列可以用 columns 关键字重新索引:

In [109]:
states = ['Texas', 'Utah', 'California']

In [110]:
frame.reindex(columns=states)  #重新排定列

Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

## 丢弃指定轴上的项

In [111]:
obj = pd.Series(np.arange(5.), index=['a', 'b', 'c', 'd',
'e'])

In [112]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [113]:
new_obj = obj.drop('c')

In [114]:
new_obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [115]:
obj.drop(['d', 'c'])

a    0.0
b    1.0
e    4.0
dtype: float64

对于 DataFrame，可以删除任意轴上的索引值。为了演示，先新建一个 DataFrame 例子:

In [116]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
                    index=['Ohio', 'Colorado', 'Utah', 'NewYork'],
                    columns=['one', 'two', 'three', 'four'])

In [117]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
NewYork    12   13     14    15

用标签序列调用 drop 会从行标签(axis 0)删除值:

In [118]:
data.drop(['Colorado', 'Ohio'])

one  two  three  four
Utah       8    9     10    11
NewYork   12   13     14    15

通过传递 axis=1 或 axis='columns'可以删除列的值:

In [120]:
data.drop('two', axis=1)

one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
NewYork    12     14    15

In [124]:
data.drop(['two', 'four'], axis='columns')

one  three
Ohio        0      2
Colorado    4      6
Utah        8     10
NewYork    12     14

会修改 Series 或 DataFrame 的大小或形状，可以就地修 改对象，不会返回新的对象:

In [125]:
obj.drop('c', inplace=True)

In [126]:
obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

小心使用 inplace，它会销毁所有被删除的数据。

## 索引、选取和过滤

Series 索引(obj[...])的工作方式类似于 NumPy 数组的索引，只不过 Series 的索引值不只是整数。

In [127]:
obj = pd.Series(np.arange(4.), index=['a', 'b', 'c', 'd'])

In [128]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [129]:
obj['b']

1.0

In [130]:
obj[1]

1.0

In [131]:
obj[2:4]

c    2.0
d    3.0
dtype: float64

In [132]:
obj[['b', 'a', 'd']]

b    1.0
a    0.0
d    3.0
dtype: float64

In [133]:
obj[[1, 3]]

b    1.0
d    3.0
dtype: float64

In [135]:
obj[obj < 2]

a    0.0
b    1.0
dtype: float64

利用标签的切片运算与普通的 Python 切片运算不同，其末端是包含的:

In [136]:
obj['b':'c']

b    1.0
c    2.0
dtype: float64

用一个值或序列对 DataFrame 进行索引其实就是获取一个或多个列:

In [6]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
                    index=['Ohio', 'Colorado', 'Utah', 'NewYork'],
                    columns=['one', 'two', 'three', 'four'])

In [7]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
NewYork    12   13     14    15

In [140]:
data['two']

Ohio         1
Colorado     5
Utah         9
NewYork     13
Name: two, dtype: int64

In [141]:
data[['three', 'one']]

three  one
Ohio          2    0
Colorado      6    4
Utah         10    8
NewYork      14   12

首先通过切片或布尔型数组选取数据:

In [142]:
data[:2]

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7

In [8]:
data[data['three'] > 5]

one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
NewYork    12   13     14    15

另一种用法是通过布尔型 DataFrame

In [9]:
data < 5

one    two  three   four
Ohio       True   True   True   True
Colorado   True  False  False  False
Utah      False  False  False  False
NewYork   False  False  False  False

In [10]:
data[data < 5] = 0

In [11]:
data

one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
NewYork    12   13     14    15

## 用 loc 和 iloc 进行选取

使用轴标签(loc)或整数索引(iloc)，从 DataFrame 选择行和列的子集。

In [12]:
data.loc['Colorado', ['two', 'three']]

two      5
three    6
Name: Colorado, dtype: int64

In [13]:
data.iloc[2, [3, 0, 1]]

four    11
one      8
two      9
Name: Utah, dtype: int64

In [15]:
data.iloc[2]

one       8
two       9
three    10
four     11
Name: Utah, dtype: int64

In [16]:
data.iloc[[1, 2], [3, 0, 1]]

four  one  two
Colorado     7    0    5
Utah        11    8    9

两个索引函数也适用于一个标签或多个标签的切片:

In [19]:
data

one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
NewYork    12   13     14    15

In [17]:
data.loc[:'Utah', 'two']

Ohio        0
Colorado    5
Utah        9
Name: two, dtype: int64

In [18]:
data.iloc[0:3][data.three > 5]

one  two  three
Colorado    0    5      6
Utah        8    9     10
NewYork    12   13     14

In [32]:
data.iloc[:,:3][data.three > 5]

one  two  three
Colorado    0    5      6
Utah        8    9     10
NewYork    12   13     14

## 整数索引

In [33]:
ser = pd.Series(np.arange(3.))

In [34]:
ser

0    0.0
1    1.0
2    2.0
dtype: float64

In [35]:
ser[-1]

KeyError: -1

pandas 可以勉强进行整数索引，但是会导致小 bug。我们有包含 0,1,2 的索引，但是引入用户想要的东西(基于标签或位置的索引)很难:

In [36]:
ser2 = pd.Series(np.arange(3.), index=['a', 'b', 'c'])

In [37]:
ser2

a    0.0
b    1.0
c    2.0
dtype: float64

In [38]:
ser2[-1]

2.0

如果轴索引含有整数，数据选取总会使用标签。为了更准确， 请使用 loc(标签)或 iloc(整数):

In [39]:
ser[:1]

0    0.0
dtype: float64

聪明的朋友已经看出iloc和loc的不同了：loc是根据dataframe的具体标签选取列，而iloc是根据标签所在的位置，从0开始计数。

In [40]:
ser.loc[:1]

0    0.0
1    1.0
dtype: float64

In [41]:
ser.iloc[:1]

0    0.0
dtype: float64

## 算术运算和数据对齐

它可以对不同索引的对象进行算术运算。在将对 象相加时，如果存在不同的索引对，则结果的索引就是该索引对的并集。对于 有数据库经验的用户，这就像在索引标签上进行自动外连接。

In [42]:
s1 = pd.Series([7.3, -2.5, 3.4, 1.5], index=['a', 'c', 'd',
'e'])

In [43]:
s2 = pd.Series([-2.1, 3.6, -1.5, 4, 3.1],
               index=['a', 'c', 'e', 'f', 'g'])

In [44]:
s1

a    7.3
c   -2.5
d    3.4
e    1.5
dtype: float64

In [45]:
s2

a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64

In [46]:
s1 + s2

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

自动的数据对齐操作在不重叠的索引处引入了 NA 值。缺失值会在算术运算过程 中传播。

对于 DataFrame，对齐操作会同时发生在行和列上:

In [48]:
df1 = pd.DataFrame(np.arange(9.).reshape((3, 3)),columns=list('bcd'),
                   index=['Ohio', 'Texas', 'Colorado'])

In [49]:
df2 = pd.DataFrame(np.arange(12.).reshape((4, 3)),columns=list('bde'),
                   index=['Utah', 'Ohio', 'Texas', 'Oregon'])

In [50]:
df1

b    c    d
Ohio      0.0  1.0  2.0
Texas     3.0  4.0  5.0
Colorado  6.0  7.0  8.0

In [51]:
df2

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

把它们相加后将会返回一个新的 DataFrame，其索引和列为原来那两个 DataFrame 的并集:

In [52]:
df1 + df2

b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN

如果 DataFrame 对象相加，没有共用的列或行标签，结果都会是空:

In [54]:
df1 = pd.DataFrame({'A': [1, 2]})

In [56]:
df2 = pd.DataFrame({'B': [3, 4]})

In [57]:
df1 

A
0  1
1  2

In [58]:
df2

B
0  3
1  4

In [59]:
df1 - df2

A   B
0 NaN NaN
1 NaN NaN

在算术方法中填充值

在对不同索引的对象进行算术运算时，你可能希望当一个对象中某个轴标签在 另一个对象中找不到时填充一个特殊值(比如 0):

In [67]:
df1 = pd.DataFrame(np.arange(12.).reshape((3, 4)),
                   columns=list('abcd'))

In [68]:
df2 = pd.DataFrame(np.arange(20.).reshape((4, 5)),
                   columns=list('abcde'))

In [69]:
df1

a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [70]:
df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   6.0   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [71]:
df2.loc[1, 'b'] = np.nan

In [72]:
df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   NaN   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

将它们相加时，没有重叠的位置就会产生 NA 值:

In [73]:
df1 + df2

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0   NaN  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

使用 df1 的 add 方法，传入 df2 以及一个 fill_value 参数:

In [74]:
df1.add(df2, fill_value=0)     

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0   5.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

它们每个都有一个副本，以字 母 r 开头，它会翻转参数。因此这两个语句是等价的:

In [75]:
1 / df1

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [76]:
df1.rdiv(1)

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

在对 Series 或 DataFrame 重新索引时，也可以指定一个填充值:

In [77]:
df1.reindex(columns=df2.columns, fill_value=0)  # 重新索引

a    b     c     d  e
0  0.0  1.0   2.0   3.0  0
1  4.0  5.0   6.0   7.0  0
2  8.0  9.0  10.0  11.0  0

## DataFrame 和 Series 之间的运算

计算一个二维数组与其某行之间的 差:

In [78]:
arr = np.arange(12.).reshape((3, 4))

In [79]:
arr

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [80]:
arr[0]

array([0., 1., 2., 3.])

In [81]:
arr - arr[0]

array([[0., 0., 0., 0.],
       [4., 4., 4., 4.],
       [8., 8., 8., 8.]])

当我们从 arr 减去 arr[0]，每一行都会执行这个操作。这就叫做广播

DataFrame 和 Series 之间的 运算差不多也是如此:

In [82]:
frame = pd.DataFrame(np.arange(12.).reshape((4, 3)),
                     columns=list('bde'),
                     index=['Utah', 'Ohio', 'Texas',
'Oregon'])

In [83]:
series = frame.iloc[0]

In [84]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [85]:
series

b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64

DataFrame 和 Series 之间的算术运算会将 Series 的索引匹配到 DataFrame 的列，然后沿着行一直向下广播:

In [87]:
frame - series

b    d    e
Utah    0.0  0.0  0.0
Ohio    3.0  3.0  3.0
Texas   6.0  6.0  6.0
Oregon  9.0  9.0  9.0

如果某个索引值在 DataFrame 的列或 Series 的索引中找不到，则参与运算的两 个对象就会被重新索引以形成并集:

In [93]:
series2 = pd.Series(range(3), index=['b', 'e', 'f'])


In [96]:
series2

b    0
e    1
f    2
dtype: int64

In [95]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [94]:
frame + series2

b   d     e   f
Utah    0.0 NaN   3.0 NaN
Ohio    3.0 NaN   6.0 NaN
Texas   6.0 NaN   9.0 NaN
Oregon  9.0 NaN  12.0 NaN

如果你希望匹配行且在列上广播，则必须使用算术运算方法。

In [97]:
series3 = frame['d']

In [98]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [99]:
series3

Utah       1.0
Ohio       4.0
Texas      7.0
Oregon    10.0
Name: d, dtype: float64

In [100]:
frame.sub(series3, axis='index')   #获取数据帧和其他元素（二元运算符子）的减法。 frame - series3

b    d    e
Utah   -1.0  0.0  1.0
Ohio   -1.0  0.0  1.0
Texas  -1.0  0.0  1.0
Oregon -1.0  0.0  1.0

## 函数应用和映射

## 排序和排名

## 带有重复标签的轴索引

# 5.3 汇总和计算描述统计

## 相关系数与协方差

## 唯一值、值计数以及成员资格

# 5.4 总结