In [79]:
#1.导入numpy库并简写为 np
import numpy as np 

In [14]:
#2. 打印numpy的版本和配置说明
print(np.__version__)
np.show_config

1.16.4


<function numpy.__config__.show()>

In [16]:
#3. 创建一个长度为10的空向量
Z = np.zeros(10)
print(Z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [18]:
#4. 如何找到任何一个数组的内存大小？
Z = np.zeros((10,10))
print("Z.size: %d" % Z.size)
print("Z.itemsize: %d" % Z.itemsize)
print("%d bytes" % (Z.size * Z.itemsize))

Z.size: 100
Z.itemsize: 8
800 bytes


In [22]:
#5. 如何从命令行得到numpy中add函数的说明文档?
np.info(np.add)


add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.  If ``x1.shape != x2.shape``, they must be
    broadcastable to a common shape (which may be the shape of one or
    the other).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or `None`,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    Values of True indicate to calculate the ufunc at that position, values
    of False indicate to leave the value in the output alone.
**kwargs
    For other keyword-only arguments, see the
    :ref:`ufunc docs <ufuncs.kwargs>`.

Returns
-------
add : ndarray or scalar
    The

In [23]:
#6. 创建一个长度为10并且除了第五个值为1的空向量
Z = np.zeros(10)
Z[4] = 1
print(Z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [24]:
#7. 创建一个值域范围从10到49的向量
Z = np.arange(10,50)
print(Z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [25]:
#8. 反转一个向量(第一个元素变为最后一个) 
Z = np.arange(50)
Z = Z[::-1]
print(Z)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


In [26]:
#9. 创建一个 3x3 并且值从0到8的矩阵
Z = np.arange(9).reshape(3,3)
print(Z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [27]:
#10. 找到数组[1,2,0,0,4,0]中非0元素的位置索引 
nz = np.nonzero([1,2,0,0,4,0])
print(nz)

(array([0, 1, 4]),)


In [28]:
#11. 创建一个 3x3 的单位矩阵
Z = np.eye(3)
print(Z)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [32]:
#12. 创建一个 3x3x3的随机数组 (3维度分别代表几个数组，每个数组中有几行 ，每个数组中有几列)
Z = np.random.random((3,1,2))
print(Z)

[[[0.52064423 0.68391268]]

 [[0.54674299 0.73081595]]

 [[0.53028857 0.20338857]]]


In [38]:
#13. 创建一个 10x10 的随机数组并找到它的最大值和最小值
Z = np.random.random((10,10))
print("Z:{}" .format(Z))
Zmin, Zmax = Z.min(), Z.max()
# print(Zmin, Zmax)
print("Zmin:{} Zmax:{}" .format(Zmin, Zmax))

Z:[[0.26656661 0.48222846 0.58073282 0.08210841 0.91216892 0.44928988
  0.78084464 0.37446702 0.02544193 0.68544313]
 [0.98729378 0.1050148  0.238703   0.0248421  0.27893294 0.96962445
  0.52173539 0.40861052 0.50353743 0.5064872 ]
 [0.85850919 0.30852638 0.14927988 0.42785568 0.66738113 0.01231122
  0.8947882  0.8129096  0.03946529 0.82604795]
 [0.78848161 0.01383259 0.37599947 0.29950282 0.31620652 0.53778636
  0.71071    0.86346955 0.89655522 0.68683946]
 [0.33185663 0.56339904 0.41411602 0.4971874  0.07432592 0.45272406
  0.49119063 0.95129465 0.34802681 0.22233351]
 [0.36998172 0.02340577 0.4518605  0.63785252 0.32784543 0.51215561
  0.77134639 0.01257938 0.2993889  0.60761476]
 [0.47839468 0.45182495 0.43631081 0.3474987  0.06380804 0.30157233
  0.38891024 0.35397372 0.31867857 0.86494255]
 [0.45474998 0.86608635 0.78318759 0.21910914 0.73418719 0.56082373
  0.69520565 0.00653194 0.82306928 0.12107114]
 [0.01566842 0.42267995 0.42275045 0.36051516 0.86275963 0.84557854
  0.852038

In [42]:
#14. 创建一个长度为30的随机向量并找到它的平均值
Z = np.random.random(30)
m = Z.mean()
print(m)
print("平局值： %f" % m)

0.47624568490031877
平局值： 0.476246


In [43]:
#15. 创建一个二维数组，其中边界值为1，其余值为0 
Z = np.ones((10,10))
Z[1:-1,1:-1] = 0
print(Z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [45]:
#16. 对于一个存在在数组，如何添加一个用0填充的边界?
Z = np.ones((5,5))
Z = np.pad(Z, pad_width=2, mode='constant', constant_values=0)
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [82]:
#17. 以下表达式运行的结果分别是什么?    (未看懂)
print(np.nan,np.inf)
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 3 * 0.1)

nan inf
nan
False
False
nan
False


In [7]:
#18. 创建一个 5x5的矩阵，并设置值1,2,3,4落在其对角线下方位置 
Z = np.diag(1+np.arange(4),k=-1)
print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [8]:
#19. 创建一个8x8 的矩阵，并且设置成棋盘样式 
Z = np.zeros((8,8),dtype=int)
Z[1::2,::2] = 1
Z[::2,1::2] = 1
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [9]:
#20. 考虑一个 (6,7,8) 形状的数组，其第100个元素的索引(x,y,z)是什么？
print(np.unravel_index(100,(6,7,8)))

(1, 5, 4)


In [10]:
#21. 用tile函数去创建一个 8x8的棋盘样式矩阵
Z = np.tile( np.array([[0,1],[1,0]]), (4,4))
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [11]:
#22. 对一个5x5的随机矩阵做归一化
Z = np.random.random((5,5))
Zmax, Zmin = Z.max(), Z.min()
Z = (Z - Zmin)/(Zmax - Zmin)
print(Z)

[[0.97956604 0.70708579 0.27486915 0.08685306 1.        ]
 [0.38802717 0.04094493 0.70986728 0.87738632 0.12061515]
 [0.84305502 0.60370109 0.06744127 0.89653659 0.        ]
 [0.93961337 0.60028142 0.15965099 0.5244039  0.60918817]
 [0.4313909  0.69521863 0.50396299 0.23209282 0.83987192]]


In [15]:
#23. 创建一个将颜色描述为(RGBA)四个无符号字节的自定义dtype？
color = np.dtype([("r", np.ubyte, 1),
                  ("g", np.ubyte, 1),
                  ("b", np.ubyte, 1),
                  ("a", np.ubyte, 1)])
color

dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

In [16]:
#24. 一个5x3的矩阵与一个3x2的矩阵相乘，实矩阵乘积是什么？
Z = np.dot(np.ones((5,3)), np.ones((3,2)))
print(Z)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


In [26]:
#25. 给定一个一维数组，对其在3到8之间的所有元素取反
Z = np.arange(11)
Z[(3 < Z) & (Z <= 8)] *= -1
print(Z)

[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]


In [27]:
#26. 下面脚本运行后的结果是什么?  (未看懂)
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

10
10


In [29]:
#27. 考虑一个整数向量Z,下列表达合法的是哪个?    （未看懂）
Z = np.arange(5)
Z ** Z  # legal

array([  1,   1,   4,  27, 256])

In [30]:
Z = np.arange(5)
2 << Z >> 2  # false

array([0, 1, 2, 4, 8])

In [31]:
Z = np.arange(5)
Z <- Z   # legal

array([False, False, False, False, False])

In [32]:
Z = np.arange(5)
1j*Z   # legal

array([0.+0.j, 0.+1.j, 0.+2.j, 0.+3.j, 0.+4.j])

In [33]:
Z = np.arange(5)
Z/1/1   # legal

array([0., 1., 2., 3., 4.])

In [35]:
Z = np.arange(5)
Z<Z>Z    # false

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [40]:
#28. 下列表达式的结果分别是什么?

In [37]:
print(np.array(0) / np.array(0))

nan


/Users/xl/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


In [38]:
print(np.array(0) // np.array(0))

0


/Users/xl/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in floor_divide
  """Entry point for launching an IPython kernel.


In [39]:
print(np.array([np.nan]).astype(int).astype(float))

[-9.22337204e+18]


In [41]:
#29. 如何从零位对浮点数组做舍入 ?
Z = np.random.uniform(-10,+10,10)
print (np.copysign(np.ceil(np.abs(Z)), Z))

[  2. -10.   4.   9.  -8.  10.   5.  -7.  -7.  -4.]


In [42]:
#30. 如何找到两个数组中的共同元素?
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
print(np.intersect1d(Z1,Z2))


[1 4 6 7]


In [45]:
#31. 如何忽略所有的 numpy 警告(尽管不建议这么做)?
#方式1:
# Suicide mode on
defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0

# Back to sanity
_ = np.seterr(**defaults)

# An equivalent way, with a context manager:

# with np.errstate(divide='ignore'):
#     Z = np.ones(1) / 0

In [46]:
#方式2：
# Suicide mode on
defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0

with np.errstate(divide='ignore'):
    Z = np.ones(1) / 0

In [47]:
#32. 下面的表达式是正确的吗?
np.sqrt(-1) == np.emath.sqrt(-1)  # False


False

In [48]:
#33. 如何得到昨天，今天，明天的日期?
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
today     = np.datetime64('today', 'D')
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print ("Yesterday is " + str(yesterday))
print ("Today is " + str(today))
print ("Tomorrow is "+ str(tomorrow))

Yesterday is 2019-08-06
Today is 2019-08-07
Tomorrow is 2019-08-08


In [49]:
#34. 如何得到所有与2016年7月对应的日期？
Z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(Z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


In [50]:
#35. 如何直接在位计算(A+B)\*(-A/2)(不建立副本)?
A = np.ones(3)*1
B = np.ones(3)*2
C = np.ones(3)*3
np.add(A,B,out=B)

array([3., 3., 3.])

In [51]:
np.divide(A,2,out=A)

array([0.5, 0.5, 0.5])

In [53]:
np.negative(A,out=A)

array([-0.5, -0.5, -0.5])

In [54]:
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5])

In [55]:
#36. 用五种不同的方法去提取一个随机数组的整数部分
Z = np.random.uniform(0,10,10)

print (Z - Z%1)

[5. 6. 7. 3. 9. 2. 0. 8. 7. 5.]


In [56]:
print (np.floor(Z))

[5. 6. 7. 3. 9. 2. 0. 8. 7. 5.]


In [57]:
print (np.ceil(Z)-1)

[5. 6. 7. 3. 9. 2. 0. 8. 7. 5.]


In [58]:
print (Z.astype(int))

[5 6 7 3 9 2 0 8 7 5]


In [59]:
print (np.trunc(Z))

[5. 6. 7. 3. 9. 2. 0. 8. 7. 5.]


In [60]:
#37. 创建一个5x5的矩阵，其中每行的数值范围从0到4
Z = np.zeros((5,5))
Z += np.arange(5)
print (Z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [61]:
#38. 通过考虑一个可生成10个整数的函数，来构建一个数组
def generate():
    for x in range(10):
        yield x
Z = np.fromiter(generate(),dtype=float,count=-1)
print (Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [62]:
#39. 创建一个长度为10的随机向量，其值域范围从0到1，但是不包括0和1
Z = np.linspace(0,1,11,endpoint=False)[1:]
print (Z)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


In [63]:
#40. 创建一个长度为10的随机向量，并将其排序 
Z = np.random.random(10)
Z.sort()
print (Z)

[0.03265644 0.06986268 0.08042863 0.38045074 0.43061365 0.59216567
 0.73469738 0.82696754 0.87353545 0.87564256]


In [64]:
#41.对于一个小数组，如何用比 np.sum更快的方式对其求和？
Z = np.arange(10)
np.add.reduce(Z)

45

In [65]:
#42. 对于两个随机数组A和B，检查它们是否相等
#方法1
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
# Assuming identical shape of the arrays and a tolerance for the comparison of values
equal = np.allclose(A,B)
print(equal)

False


In [66]:
# 方法2
# Checking both the shape and the element values, no tolerance (values have to be exactly equal)
equal = np.array_equal(A,B)
print(equal)

False


In [67]:
#43. 创建一个只读数组(read-only)
# 使用如下过程实现
Z = np.zeros(10)
Z.flags.writeable = False
Z[0] = 1

ValueError: assignment destination is read-only

In [68]:
#44. 将笛卡尔坐标下的一个10x2的矩阵转换为极坐标形式
Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print (R)
print (T)

[0.70968834 0.59384006 0.78844521 1.01864101 0.80483988 1.05440512
 0.40345943 0.96378805 0.41938555 1.30542362]
[1.53448809 0.626471   1.54101569 1.29899515 0.89712029 0.91234257
 0.86582465 0.84815756 0.2077874  0.71619166]


In [69]:
#45. 创建一个长度为10的向量，并将向量中最大值替换为1
Z = np.random.random(10)
Z[Z.argmax()] = 0
print (Z)

[0.43803388 0.9114607  0.         0.48602231 0.68380493 0.67687867
 0.10248103 0.51675548 0.8950629  0.39486349]


In [70]:
#46. 创建一个结构化数组，并实现 x 和 y 坐标覆盖 [0,1]x[0,1] 区域
Z = np.zeros((5,5), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))
print(Z)


[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


In [71]:
#47. 给定两个数组X和Y，构造Cauchy矩阵C (Cij =1/(xi - yj))¶
X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))


3638.1636371179666


In [73]:
#48. 打印每个numpy标量类型的最小值和最大值？
for dtype in [np.int8, np.int32, np.int64]:
    print(np.iinfo(dtype).min)
    print(np.iinfo(dtype).max)


-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807


In [74]:

for dtype in [np.float32, np.float64]:
    print(np.finfo(dtype).min)
    print(np.finfo(dtype).max)
    print(np.finfo(dtype).eps)

-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


In [87]:
#49. 如何打印一个数组中的所有数值?
np.set_printoptions(threshold=np.nan)
Z = np.zeros((16,16))
print (Z)

ValueError: threshold must be numeric and non-NAN, try sys.maxsize for untruncated representation

In [81]:
#50. 给定标量时，如何找到数组中最接近标量的值？
Z = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(Z-v)).argmin()
print (Z[index])

37
